#!/bin/bash
sudo: required
services: docker

addons:
  apt:
    packages:
      - docker-ce

env:
  - CONTAINER=robot
  - BASE=ubuntu
  - VERSION=1.0.0
  - LATEST_VERSION=1.0.0
  - LATEST_BASE=ubuntu

install:
  - git clone --recurse-submodules https://github.com/8ear/MISP-dockerized-documentation.git ~/misp-docs

script:
  - travis_retry build.sh ${VERSION}-${BASE}
  - ~/misp-docs/official-images/test/run.sh "dcso/misp-${CONTAINER}:$VERSION"


after_sucess:
  - docker tag dcso/misp-${CONTAINER}:${VERSION}-${BASE}
  - docker tag dcso/misp-${CONTAINER}:${LATEST_VERSION}-${LATEST_BASE} dcso/misp-${CONTAINER}:latest

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  provider: script
  script: 
    docker push dcso/misp-${CONTAINER}:${VERSION}-${BASE}
    docker push dcso/misp-${CONTAINER}:latest
  on:
    branch: develop

# vim:set et ts=2 sw=2: